repositories:
  - name: example-grant-with-auth
    repository: DEFRA/grants-config-example-grants
    path: configurations/example-grant-with-auth
  - name: pigs-might-fly
    repository: DEFRA/grants-config-example-grants
    path: configurations/pigs-might-fly
  - name: woodland
    repository: DEFRA/grants-config-woodland
    path: configurations/woodland
  - name: playground-grant
    repository: DEFRA/grants-config-playground
    path: configurations/playground-grant
  - name: land-grants
    repository: DEFRA/grants-config-land-grants
    path: configurations/land-grants
  - name: farm-payments
    repository: DEFRA/grants-config-farm-payments
    path: configurations/farm-payments
  - name: grasslands
    repository: DEFRA/grants-config-grasslands
    path: configurations/grasslands
