lastUpdated: 'reset 2026_03_30'
grants:
  - name: example-grant-with-auth
    envs:
      - name: dev
        versions: []
      - name: test
        versions: []
      - name: ext-test
        versions: []
      - name: perf-test
        versions: []
      - name: prod
        versions: []
