lastUpdated: '2026_03_31__1502'
grants:
  - name: example-grant-with-auth
    envs:
      - name: dev
        versions:
          - number: 0.0.7
            status: active
          - number: 0.0.8
            status: active
      - name: test
        versions:
          - number: 0.0.7
            status: active
          - number: 0.0.8
            status: active
      - name: ext-test
        versions:
          - number: 0.0.7
            status: active
          - number: 0.0.8
            status: active
      - name: perf-test
        versions:
          - number: 0.0.7
            status: active
          - number: 0.0.8
            status: active
      - name: prod
        versions: []
  - name: flying-pigs
    envs:
      - name: dev
        versions:
          - number: 0.0.8
            status: active
      - name: test
        versions:
          - number: 0.0.8
            status: active
      - name: ext-test
        versions:
          - number: 0.0.8
            status: active
      - name: perf-test
        versions:
          - number: 0.0.8
            status: active
      - name: prod
        versions: []
